#!/usr/bin/env python3
"""
Xal's Compendium - converts .github/data/catalog_data.json (real quest IDs +
names, produced by extract_quests.py) into a loadable Lua file the addon can
actually read - WoW addons only load .lua/.xml declared in the .toc, not
arbitrary JSON.

Output goes into a single "Uncategorized" category under Current -> Daily,
NOT sorted into real Daily/Weekly/category buckets - that sorting still
needs a human review pass (there's no reliable way to auto-detect which
tier/type/category a quest belongs to from just its id+name). This is a
stopgap so real quest names show up on the tracker immediately as data
comes in, instead of nothing - proper categorization happens over time as
someone reviews and moves entries into their real spots.

Run manually (python3 .github/scripts/generate_catalog_lua.py) any time
catalog_data.json has new entries - safe to re-run, fully regenerates the
output file from scratch each time.
"""
import json
import os

CATALOG_DATA_PATH = ".github/data/catalog_data.json"
OUTPUT_PATH = "GeneratedCatalog.lua"


def main():
    if not os.path.exists(CATALOG_DATA_PATH):
        print(f"{CATALOG_DATA_PATH} doesn't exist yet - nothing to convert.")
        return 0

    with open(CATALOG_DATA_PATH, encoding="utf-8") as fh:
        catalog = json.load(fh)

    if not catalog:
        print("catalog_data.json is empty - nothing to convert.")
        return 0

    lines = [
        "-- AUTO-GENERATED by .github/scripts/generate_catalog_lua.py - DO NOT EDIT BY HAND.",
        "-- Real quest data from the extraction pipeline, dumped into a single",
        "-- Uncategorized holding category until someone sorts each one into its",
        "-- real Daily/Weekly/category spot. Loaded by XalsCompendium.toc after Data.lua.",
        "",
        "local currentTier = XComp.Data.Catalog.tiers[1]",
        "local dailyType = currentTier.types[1]",
        "local uncategorized = dailyType.categories[8] -- Custom, used as the holding area",
        "",
    ]

    # Sorted by ID for stable, diffable output across regenerations.
    for quest_id in sorted(catalog.keys(), key=int):
        entry = catalog[quest_id]
        # entry is now the FULL raw API response (extract_quests.py stores
        # everything, not just name, so future categorization logic has
        # real field data to work with) - the actual title field name
        # wasn't documented anywhere reliable, so check both possibilities.
        name = entry.get("title") or entry.get("name") or ""
        # Escape quotes/backslashes so a quest name can never break the Lua string.
        safe_name = name.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            f'table.insert(uncategorized.items, {{ uid = "quest-{quest_id}", '
            f'name = "{safe_name}", questID = {quest_id}, children = {{}} }})'
        )

    with open(OUTPUT_PATH, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"Wrote {len(catalog)} entries to {OUTPUT_PATH}.")
    return 0


if __name__ == "__main__":
    exit(main())
